<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ynohW8-64b-one" name="HBTestesNG.TestCases.Test_VoiceACD_Basic" tests="3" failures="1" timestamp="26 Aug 2017 09:23:41 GMT" time="335.416" errors="0">
  <testcase name="VoiceACD_Q_Answer" time="129.437" classname="HBTestesNG.TestCases.Test_VoiceACD_Basic">
    <failure type="java.lang.AssertionError" message="VoiceACD-&gt;Q-&gt;Answered has failed because =&gt; 
@ agent1yc1@c1yc1.comfail on =&gt; btnAnswer expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: VoiceACD->Q->Answered has failed because => 
@ agent1yc1@c1yc1.comfail on => btnAnswer expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at HBTestesNG.BaseObjects.TestCaseObject.failTest(TestCaseObject.java:317)
	at HBTestesNG.BaseObjects.TestCaseObject.endTestCase(TestCaseObject.java:200)
	at HBTestesNG.TestCases.Test_VoiceACD_Basic.VoiceACD_Q_Answer(Test_VoiceACD_Basic.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- VoiceACD_Q_Answer -->
  <testcase name="VoiceACD_NoQ_Answer" time="90.861" classname="HBTestesNG.TestCases.Test_VoiceACD_Basic"/>
  <testcase name="VoiceACD_NoQ_Answer_NoWrapTime" time="115.118" classname="HBTestesNG.TestCases.Test_VoiceACD_Basic"/>
</testsuite> <!-- HBTestesNG.TestCases.Test_VoiceACD_Basic -->
